from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_chroma import Chroma
from langchain_community.llms import HuggingFacePipeline
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer, pipeline

# 1. Connect to persistent ChromaDB
persist_directory = "./chroma_db"
embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

vector_store = Chroma(
    persist_directory=persist_directory,
    embedding_function=embeddings
)

print("Connected to ChromaDB vector store successfully.")

# 2. Trigger an Anomaly
query_trigger = "ERROR Database connection timeout"
print(f"\n[ALERT] Anomaly Detected matching trigger criteria: '{query_trigger}'")

# 3. Retrieve Context via RAG
relevant_docs = vector_store.similarity_search(query_trigger, k=2)
context_text = "\n".join([doc.page_content for doc in relevant_docs])

print("\nRetrieved Context from Vector Database:")
for i, doc in enumerate(relevant_docs, 1):
    print(f"  [Context Log {i}]: {doc.page_content}")

# 4. Initialize Local LLM with proper generation config to avoid loops
print("\nLoading local LLM (google/flan-t5-small) for dynamic reasoning...")
model_id = "google/flan-t5-small"
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForSeq2SeqLM.from_pretrained(model_id)

pipe = pipeline(
    "text2text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=64,
    do_sample=False,        # Use greedy decoding to prevent repetitive loops
    repetition_penalty=2.5  # Penalize repeating tokens
)
llm = HuggingFacePipeline(pipeline=pipe)

# 5. Few-shot prompt pattern to force actual diagnostic reasoning instead of echoing
prompt = (
    f"Task: Provide a root cause and fix.\n"
    f"Log: 2026-09-18 10:10:45 ERROR Database connection timeout on /api/v1/data\n"
    f"Fix: Check database service health, review network security groups, and increase connection timeout thresholds.\n\n"
    f"Task: Provide a root cause and fix.\n"
    f"Log: {context_text}\n"
    f"Fix:"
)

print("\n--- Autonomous RAG Diagnostic Summary (Generated by LLM) ---")
response = llm.invoke(prompt)
print(response.strip())