services:
  anomaly_engine:
    build: .
    container_name: anomaly_rag_engine
    ports:
      - "8501:8501"
    volumes:
      - ./chroma_db:/app/chroma_db
    command: ["streamlit", "run", "app.py", "--server.address=0.0.0.0"]